# Generated by Django 6.0.3 on 2026-03-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='good_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(default='-', max_length=9),
        ),
        migrations.AddField(
            model_name='student',
            name='locker_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='personal_email',
            field=models.EmailField(default='example@personal.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='example@school.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
