# Generated by Django 6.0.3 on 2026-03-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_rename_studnet_grade_student'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('a_subject', 'student'), name='unique_student_subject'),
        ),
    ]
