# Generated by Django 6.0.3 on 2026-03-09 19:11

import student_app.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0009_grade_unique_student_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[student_app.validator.validate_low_grade, student_app.validator.validate_high_grade]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.CharField(default='Professor Cahan', validators=[student_app.validator.validate_professor_name]),
        ),
    ]
