# Generated by Django 6.0.3 on 2026-03-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0010_alter_grade_grade_alter_subject_professor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grade',
            name='unique_student_subject',
        ),
    ]
