# Generated by Django 6.0.3 on 2026-03-09 16:50

import django.db.models.deletion
import student_app.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_student_good_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default=None, unique=True, validators=[student_app.validator.validate_subject_name])),
                ('professor', models.CharField(default='Mr. Cahan', validators=[student_app.validator.validate_professor_name])),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(default='12-12-12', max_length=9, validators=[student_app.validator.validate_combination]),
        ),
        migrations.AlterField(
            model_name='student',
            name='locker_number',
            field=models.PositiveSmallIntegerField(default=110, unique=True, validators=[student_app.validator.validate_locker_number_low, student_app.validator.validate_locker_number_high]),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=None, max_length=255, validators=[student_app.validator.validate_name_format]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default=None, max_length=254, unique=True, validators=[student_app.validator.validate_school_email]),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[student_app.validator.validate_grade])),
                ('studnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
                ('a_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(through='student_app.Grade', to='student_app.subject'),
        ),
    ]
