# Generated by Django 6.0.3 on 2026-03-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_subject_alter_student_locker_combination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='studnet',
            new_name='student',
        ),
    ]
