# Generated by Django 6.0.3 on 2026-03-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_grade_unique_student_subject'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grade',
            name='unique_student_subject',
        ),
    ]
