# Use postgres/example user/password credentials
services: 
  web:
    build: .
    image: dj-container
    container_name: dj-container
    command: [sh, -c, "python manage.py migrate && 
                      python manage.py createsuperuser --no-input &&
                      python manage.py loaddata test_data.json &&
                      python manage.py runserver 0.0.0.0:8000"]
    ports: 
      - "8000:8000"
    environment:
      DJANGO_SUPERUSER_USERNAME: test
      DJANGO_SUPERUSER_PASSWORD: test
      DJANGO_SUPERUSER_EMAIL: test@email.com
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: db-container
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: school_db
    ports:
      - "5433:5432"
    healthcheck:  #https://www.codegenes.net/blog/django-docker-connection-to-server-at-localhost-127-0-0-1-port-5432-failed/
      test: ["CMD-SHELL", "pg_isready -U test -d school_db"]  # Check if PostgreSQL is ready  
      interval: 5s           # Check every 5 seconds  
      timeout: 5s            # Timeout after 5 seconds  
      retries: 5             # Retry 5 times before marking as unhealthy  
