# Generated by Django 6.0.3 on 2026-03-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age', models.BigIntegerField()),
                ('name', models.CharField()),
                ('vaccinated', models.BooleanField(default=False)),
                ('species', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('breed', models.CharField()),
                ('age', models.BigIntegerField()),
                ('vaccinated', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age', models.BigIntegerField()),
                ('name', models.CharField()),
                ('vaccinated', models.BooleanField(default=False)),
                ('breed', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExoticAnimal',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('region_of_origin', models.CharField()),
                ('name', models.CharField()),
                ('age', models.BigIntegerField()),
                ('type_of_animal', models.CharField()),
                ('vaccinated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('age', models.BigIntegerField()),
                ('number_of_pets', models.BigIntegerField()),
            ],
        ),
    ]
